# Site settings
title: OasisCom - Documentacion
email: info@oasiscom.com
description: >
  La mejor forma de conocer y usar OasisCom.
baseurl: ""
url: "http://localhost:4000"
twitter_username: oasiscom
github_username:  oasiscom

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
markdown: kramdown
theme: jekyll-theme-slate
repository: OasisCom/manuals
